### ISSUE TITLE
Is first connection really necessary?

### ISSUE THREAD

**Issue by theRemoter** [Tukks/haierV300SApi#1]
Hi, thanks for the great documentation!

My question is:
1. does it really necessary to send the first GET request: `http://<ipOfYourTV>:56790/dd.xml` or can I skip it and right away send post messages to `http://<ipOfYourTV>:56789/apps/SmartCenter` ?
2. if I must send the first GET message, do I really need to add the header of `Connection: Keep-alive` ?

Thanks

**Comment by Tukks** [comment]
Hello,

No, I think is not necessary.
on Openhab (my home automation system)
I just need to do something like this :
`sendHttpPostRequest("http://192.168.1.48:56789/apps/SmartCenter", "", "<remote><key code=1006/></remote>");`

i didn't update the doc.

**Comment by theRemoter** [comment]
thx and how did u got the port? is it always the same on your tv?

**Comment by Tukks** [comment]
Yes, always this one, I get the port when I sniffed the packet from my TV.
