### ISSUE TITLE
haier app

### ISSUE THREAD

**Issue by theRemoter** [Tukks/haierV300SApi#2]
Hi!

I tried to create a project app inspired by your work.
i did it so it should support also other aps by vestel like the tv u used, but I cannot verify if it's working on your haier because I don't have this tv model.
I have posted my project here-
https://github.com/theRemoter/VestelProject

do u have a discord account or maybe an email we can discuss or maybe can u check out my project and see if it's also working for u?

**Comment by Tukks** [comment]
Hello,

thank for you project.
Sadly I changed my television 2 month ago.
Seems a great project BTW.

I
